### ISSUE TITLE
consul_acl created on every puppet run

### ISSUE THREAD

**Issue by horsehay** [solarkennedy/puppet-consul#211]
The consul_acl resource I'm creating is getting created on every puppet run.

``` puppet
      consul_acl { 'rule':
        ensure        => 'present',
        rules         => {
          'key' => {
            '' => {
              'policy' => 'read'
            }
          }
        },
        type          => 'management',
        acl_api_token => $acl_master_token,
      }
```

This is problematic because there appear to have been changes on every run. Is there an issue with the custom type/provider? Is anyone else seeing this?

**Comment by solarkennedy** [comment]
This is a pretty common issue on puppet types/providers. Can you post some more data? (like the output of the 2 consecutive puppet runs and the actual json output of the api?)

**Comment by sigerber** [comment]
We're experiencing the same thing. I think the issue here is that there is no 'prefetch' method so the property_hash is always empty. Therefore puppet thinks it always has to create the resource again. I've managed to fix this on a local copy.  

I'll can try putting together a pull request tomorrow if you like.

**Comment by solarkennedy** [comment]
Huh, I thought `prefetch` wasn't strictly required, just an optimization, and that you really needed `instances`, but I guess we are lacking both :(

Bonus points for implementing instances, we'll be able to run `puppet resource consul_acl` and it will spit out live puppet code! (in theory)

**Comment by horsehay** [comment]
@sigerber: Good catch. I've not used prefetch in the modules I've built, so a PR would be awesome. Thanks!

**Comment by sigerber** [comment]
I think from reading http://garylarizza.com/blog/2013/12/15/seriously-what-is-this-provider-doing/ that prefetch was the key. Certainly that was enough to get our idempotency beaker test work. But I'm pretty new to puppet... I've submitted a PR for prefetch, but I couldn't think of a way to make instances work - since it doesn't take parameters. You'd need to be supplied or discover the port and a token with sufficient privileges.
