### ISSUE TITLE
Support for External Services 

### ISSUE THREAD

**Issue by brettswift** [solarkennedy/puppet-consul#252]
https://www.consul.io/docs/guides/external.html

This is something I was just looking for.  It'd be nice to have a list of external service declaration in hiera.

Assuming a puppet master, these DNS entries would only come and go when Puppet runs - so the lifecycle and use case is different than other services.

Has there been conversation about this before?  Is this something other people would want?

**Comment by solarkennedy** [comment]
As far as I know nobody has asked for this yet. I would assume in the design that the service would not be ephemeral, that someone would have to say ensure=>absent if they wanted the service to go away.

It is a little tricky and would require some ruby chops to do this as they would have to do a real type/provider on the catalog api: https://www.consul.io/docs/agent/http/catalog.html

**Comment by brettswift** [comment]
Yea I was wondering if there would be a way of marking all external resources so you wouldn't have to do the `ensure => absent` thing.   Could get a little intensive searching for resources not in the catalog and executing the `deregister` dynamically, depending on how heavy you were to use this feature.

You're right though, external services in consul aren't ephemeral - the example consul docs use aliases `www.google.com`.  Whereas our use case is more for automating some DNS from puppet of non-puppet servers.   We're leveraging consul because our crufty "enterprise" has a pokey and slow email process to create DNS entries.  😢

A simpler yet more hacky implementation that we might use if this doesn't go into the module is just a defined type with a dirty exec to curl command.  With windows support coming, that won't suffice for this module.

I'm not sure when I could spend some time on the type & provider but if I were to,  is this something you'd take into the module?

**Comment by solarkennedy** [comment]
Well if the provider were written and implemented the `self.instances` method, then you could do this:

```
resources { 'consul_external_service':
  purge => true,
}
```

It wouldn't be that intensive because you would probably just end up calling the `prefetch` method, which would only have to call a single endpoint: https://www.consul.io/docs/agent/http/catalog.html#catalog_services
nbd.

And then any discovered services that were not in the catalog would be purged automatically. (see also http://www.xkyle.com/writing-purgable-puppet-code/)


I would absolutely accept a PR with such a provider, even if it didn't implement instances. Providers are not super easy, but there is prior art with `consul_acl`. There is also room for tests (unit as well as acceptance/integration, although I need to work on getting the itests working in travis all the time)
