### ISSUE TITLE
Run configtest before reloading service

### ISSUE THREAD

**Issue by nvtkaszpir** [solarkennedy/puppet-consul#338]
Puppet should run config test prior restarting service:
```bash
consul configtest -config-dir ...
```

Currently config_hash can get any key/value which can be not understood by consul, thus failing to start service.

**Comment by solarkennedy** [comment]
That would be cool. Now we could do that at the init script level because we control all of them:
https://github.com/solarkennedy/puppet-consul/tree/master/templates

I don't know if all init types are amenable to that though. 

If we wanted to do it with a puppet exec, I think we would want to use something like this:
https://github.com/puppetlabs/puppetlabs-transition

To be able to run that exec *before* the service is restarted.

Or we could just put it in 
https://github.com/solarkennedy/puppet-consul/blob/master/manifests/reload_service.pp

We would just need to make sure that properly notifies the service below.

**Comment by solarkennedy** [comment]
We tried this, and it didn't work so great.
