### ISSUE TITLE
Annoying "defined 'protocol' as 'http'" for every consul_prepared_query resource

### ISSUE THREAD

**Issue by asmajlovic** [solarkennedy/puppet-consul#410]
In line with #310 and #342, the prepared query provider/type appears to suffer from the same issue:

```
[vagrant.local] ~ # puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for vagrant.local
Info: Applying configuration version '1521054150'
Notice: /Stage[main]/Mpsconsul::Server/Consul_prepared_query[test-backupdaemon]/protocol: defined 'protocol' as 'http'

[vagrant.local] ~ # puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for vagrant.local
Info: Applying configuration version '1521054150'
Notice: /Stage[main]/Mpsconsul::Server/Consul_prepared_query[test-backupdaemon]/protocol: defined 'protocol' as 'http'
```

**Comment by jardleex** [comment]
Hi,

seems we stumbled over the same issue.
We want to deploy a catch-all template of a prepared query with Puppet while omitting the name in order to ease the ACL setup. If no `name` key is given, the name given to the define is used. If we set `name => '',` we see the issue described above. Setting `protocol => 'http',` when calling `consul_prepared_query` ain't changed the behavior.

**Comment by khdevel** [comment]
I have prepared some fix for it and I hope it will be implemented in the newest version of this module... it works fine on my Consul's cluster.
